GOLDEN_GRAMMAR ?= ../../data/golden_grammars/golden_grammar_calc.json
LDFLAGS := -lstdc++
KLEEFLAGS := --disable-verify -libcxx

ORIG_SRCS := parser_orig.cpp
SRCS := parser_symex.cpp

include ../common.mk