TOKEN_CURSOR ?= true
TOKENIZATION_FUNCTION ?= next_sym

GOLDEN_GRAMMAR ?= ../../data/golden_grammars/golden_grammar_tinyc.json

ORIG_SRCS := tiny_orig.c
SRCS := tiny_symex.c ../__common__/common.c

include ../common.mk