TOKEN_CURSOR ?= true
TOKENIZATION_FUNCTION ?= pnext

GOLDEN_GRAMMAR ?= ../../data/golden_grammars/golden_grammar_mjs.json

ORIG_SRCS := mjs_orig.c
SRCS := mjs_symex.c ../__common__/common.c

include ../common.mk